# Generated by Django 5.1.2 on 2024-11-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', '출석'), ('absent', '결석')], max_length=10),
        ),
    ]
